// @elfui/chain — 链式编程体验包
//
// 这个包面向旧站渐进嵌入、小 demo、其它框架局部增强等场景。
// 它会注入 runtime compiler，因此支持 createComponent().template(...)。

import { compile } from "@elfui/compiler/compile";
import { createComponent, defineComponent, extend, setTemplateCompiler, variant } from "./builder";
import { globalStyle, registerComponents, theme, type RenderFn } from "@elfui/runtime";

setTemplateCompiler((template) => compile(template) as unknown as RenderFn);

export { compile, type CompileOptions, type RenderFunction } from "@elfui/compiler/compile";

export {
  effectScope,
  getCurrentScope,
  isProxy,
  isReadonly,
  isState,
  markRaw,
  nextTick,
  onScopeDispose,
  onWatcherCleanup,
  readonly,
  toRaw,
  toValue,
  unref,
  useComputed,
  useComputed as computed,
  useEffect,
  useReactive,
  useRef,
  useShallowReactive,
  useShallowRef,
  watch,
  watchEffect,
  watchPostEffect,
  watchSyncEffect
} from "@elfui/reactivity";

export {
  ElementBuilder,
  createComponent,
  defineComponent,
  extend,
  setTemplateCompiler,
  variant,
  type DefineComponentOptions,
  type ExtendableComponent,
  type InferPropsOptions,
  type VariantConfigurator
} from "./builder";

export {
  captureError,
  configure,
  createFormControlContext,
  createInjectionKey,
  defineCustomElement,
  defineExpose,
  directive,
  ensureCustomElement,
  errorBoundary,
  getConfig,
  globalStyle,
  hasInjectionContext,
  inject,
  onActivated,
  onAttributeChanged,
  onBeforeMount,
  onBeforeUnmount,
  onBeforeUpdate,
  onDeactivated,
  onErrorCaptured,
  onMount,
  onUnmount,
  onUpdated,
  provide,
  projectLightDom,
  registerComponents,
  resetConfig,
  resetDirectives,
  resetGlobalStyles,
  resolveComponentTag,
  theme,
  useAttrs,
  useClickOutside,
  useEscapeKey,
  useEventListener,
  useFormControlContext,
  useHost,
  useHostAttr,
  useHostClass,
  useHostCssVar,
  useHostFlag,
  useHostStyle,
  useModel,
  usePlugin,
  useRenderRoot,
  useScopedSlot,
  useScrollLock,
  useShadowRoot,
  useTemplateRef,
  type AnyPropType,
  type ComponentDefinition,
  type ComponentEmitMap,
  type ComponentRegistryInput,
  type ComponentSlotMap,
  type DefineCustomElementOptions,
  type DirectiveBinding,
  type DirectiveDefinition,
  type DirectiveFn,
  type DirectiveHooks,
  type DirectiveUnregister,
  type ElfElementConstructor,
  type ElfUIConfig,
  type ElfUIPlugin,
  type ElfUIPluginContext,
  type ElfUIPluginFn,
  type ElfUIPluginObject,
  type EmitOptions,
  type ErrorBoundarySlots,
  type FormControlContext,
  type FormControlOptions,
  type FormControlRule,
  type FormControlValidationResult,
  type FormControlValue,
  type HostClassValue,
  type InjectionKey,
  type LightDomProjectionController,
  type LightDomProjectionOptions,
  type LightDomProjectionTarget,
  type ModelRef,
  type PropOption,
  type PropType,
  type PropsOptions,
  type RenderContext,
  type RenderFn,
  type ScopedSlotFn,
  type SetupContext,
  type SetupFn,
  type StyleDisposer,
  type StyleInjectionOptions,
  type ThemeTarget,
  type UseModelOptions
} from "@elfui/runtime";

export const ElfUI = {
  createComponent,
  defineComponent,
  extend,
  registerComponents,
  globalStyle,
  theme,
  variant
};
